import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
  AiFillHeart,
} from "react-icons/ai";
import Image from "next/image";
import adi from "../public/hello.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import im1 from "../public/chatFinal.png";
import im2 from "../public/newsfinal.png";
import im3 from "../public/nodefinal.png";
import im4 from "../public/textfinal.png";
import im5 from "../public/web5.png";
import im6 from "../public/web6.png";
import im7 from "../public/cppimg.png";
import im8 from "../public/JavaScript.png";
import im9 from "../public/HTML.png";
import im10 from "../public/CSS.png";
import im11 from "../public/Python.png";
import im12 from "../public/Dart.png";
import im13 from "../public/reactjs.png";
import im14 from "../public/next.png";
import im15 from "../public/flut.jpg";
import im16 from "../public/node.png";
import im17 from "../public/git.png";
import im18 from "../public/github.png";
import im19 from "../public/gitlab.png";
import { useState } from "react";




export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aditya Shitale portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        {/* ****************************section 1 starts***************************************** */}

        <section className="min-h-screen">
          {/* ****************************Navbar containing resume and dark mode button************** */}

          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons  dark:text-white">
              DevelopedbyAdi
            </h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-2xl">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  target="_blank"
                  href="https://drive.google.com/file/d/1mTl5d39cg0njSroEPar7_zDRs-cuV6t_/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* ****************Name and basic information about myself*************** */}
          <div className="text-center p-10 " >
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl " >
              Aditya Shitale
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl  dark:text-white">
              Developer and Coder.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto  dark:text-white">
              I am a student at Indian Institute of Information
              Technology,Kottayam, currently pursuing B.Tech in computer Science
              (2024),You can contact me from Clicking below.
            </p>
          </div>

          {/* *********************React icons with contact details************************ */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-white" data-aos="fade-right" >
            <a href="https://twitter.com/AdityaShitale" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/aditya-shitale-664991214/"
              target="_blank"
            >
              {" "}
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Aditya-Shitale" target="_blank">
              {" "}
              <AiFillGithub />
            </a>
            <a href="mailto:adityashitale4@gmail.com" target="_blank">
              {" "}
              <AiFillMail />
            </a>
          </div>

          {/* ****************emoji icon saying hi to visitor****************** */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 motion-safe:animate-fadeIn">
            <Image src={adi} alt="" layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* ***************************SECTION 2 start************************************* */}
        <section>
          {/* *****************************services i offer and description about it**************************** */}
          <div>
            <h3 className="text-3xl py-1 font-bold  dark:text-white">
              Skills I have
            </h3>
            <p className="text-md font-serif py-2 leading-8 text-gray-800  dark:text-white">
              I am a sophomore at{" "}
              <span className="text-teal-500">
                Indian Institute of Information Technology, Kottayam
              </span>{" "}
              and have had the experience of developing and working on projects
              as a part of open source events. I have experience in working with
              many Javascript Libraries and Frameworks such as ReactJS for
              frontend and NodeJS as Backend. Also well versed in C++ . I am a
              flexible developer and a quick learner of new tech stacks. Would
              love to talk more about my projects over a meeting. Excited at the
              prospect of working as an Intern.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I offer from a wide range of services, including frontend development,
              backend development,App developement,Web developement.
            </p>
          </div>
          {/* ***************************Card explaining SKills**************************** */}
          {/* *****************card #1************** */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-2xl p-10 rounded-xl  my-10   dark:bg-white">
              <Image
                src={design}
                alt=""
                loading="lazy"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Languages</h3>
              <p className="py-2">
              Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Languages  I use</h4>
            <div> <Image className="display: inline hover:scale-150 duration-300" src={im7} alt="C++" height={50}/><p className="text-gray-800 font-bold py-1 pb-5">C++</p></div>
           <div> <Image className="display: inline hover:scale-150 duration-300" src={im8} alt=""height={50}/>  <p className="text-gray-800 font-bold py-1 pb-5">JavaScript</p> </div>
           <div> <Image className="display: inline hover:scale-150 duration-300" src={im9} alt=""height={50}/>  <p className="text-gray-800 font-bold py-1">HTML</p></div>
           <div> <Image className="display: inline hover:scale-150 duration-300" src={im10} alt=""height={50}/> <p className="text-gray-800 font-bold py-1">CSS</p></div>
           <div> <Image className="display: inline hover:scale-150 duration-300" src={im11} alt=""height={50}/> <p className="text-gray-800 font-bold py-1">Python</p></div>
           <div> <Image className="display: inline hover:scale-150 duration-300" src={im12} alt=""height={50}/> <p className="text-gray-800 font-bold py-1">Dart</p></div>
            </div>

            {/* *****************card #2************** */}

            <div className="text-center shadow-2xl p-10 rounded-xl  my-10 dark:bg-white">
              <Image src={code} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Framework</h3>
              <p className="py-2">
              Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Frameworks tools I use</h4>
             <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im13} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">ReactJs</p></div> 
             <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im16} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">NodeJs</p></div> 
             <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im14} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">Next.js</p></div> 
             <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im15} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">Flutter</p></div> 
            </div>

            {/* *****************card #3************** */}

            <div className="text-center shadow-2xl p-10 rounded-xl  my-10 dark:bg-white">
              <Image src={consulting} alt="" width={100}  height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">tools i use</h3>
              <p className="py-2 ">
              Creating elegant designs suited for your needs following core
                design theory.
              </p>
             <h4 className="py-4 text-teal-600">tools I use</h4>
              <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im17} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">Github</p> </div>
              <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im18} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">bash</p></div>
              <div> <Image  className="display: inline hover:scale-150 duration-300" height={50} src={im19} alt=""/> <p className="text-gray-800 font-bold py-1 pb-5">Gitlab</p></div>
        
            </div>
          </div>
        </section>

        {/* ***************************SECTION 3 start************************************* */}

        <section>
          {/* ***************************portfolio explaining about my projects and experiences************************** */}
          <div>
            <h3 className="text-3xl py-1 font-bold  dark:text-white">Portfolio</h3>
            <p className="text-md font-serif py-2 leading-8 text-gray-800  dark:text-white">
              Since the start I am working as individual and created projects to
              gain
              <span className="text-teal-500"> Knowledge </span>
              and to improve my<span className="text-teal-500"> Skills. </span>
              Being a Junior at college, I have had the experience of creating
              and also working on projects just for fun that has a good user
              experience meanwhile being scalable and efficient under the hood.
              I use NodeJS/FastAPI for the backend of most of the projects that
              I make which have a ReactJS frontend.I also have basic Idea about
              Flutter for App development.
            </p>
            <p className="text-md py-2 leading-8 font-burtons text-gray-800 dark:text-white">
              Checkout my other projects............!  !  !
            </p>
            <p className="font-serif text-md dark:text-white">Click on the image to go on respective repository</p>
          </div>
<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

   {/* ***************************CHATAPP pic with info***************************** */}
  <div className="basis-1/3 flex-1 ">
    <div className="relative">
      <a href="https://github.com/Aditya-Shitale/Chat-App" target="_blank">
          <Image src={im1} className="rounded-lg object-cover hover:scale-110 duration-300"  w-full  h-full  layout="responsive"  alt="" />
             <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-gray-800 opacity-70">
                <p className="text-lg text-orange-500 font-bold">  Chat-App</p>
                  <p className="text-xs text-teal-500">This a is chat Application based on React-Js and backend as firebase, here you can create an account by unique mail id's and also can set your profile picture, find friends by searching if they have an account on app</p>
             </div>
      </a>
     </div>

  </div>

      {/* ***************************NEWS MEDIA pic with info***************************** */}

    <div className="basis-1/3 flex-1">
      <div className="relative">
         <a href="https://github.com/Aditya-Shitale/News_Media" target="_blank">
              <Image src={im2}  className="rounded-lg object-cover hover:scale-110 duration-300"  w-full  h-full  layout="responsive"  alt="" />
                <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-gray-800 opacity-70">
                  <p className="text-lg text-orange-500 font-bold">NEWSMEDIA- a live news app</p>
                    <p className="text-xs text-teal-500">This is a site where you can see live news Build using React-Js with help of news API, various sections are made for different types of news.</p>
             </div>
          </a>
      </div>    
    </div>



   {/* ***************************CLOUDNOTEBOOK pic with info***************************** */}

    <div className="basis-1/3 flex-1">
      <div className="realtive">
        <a href="https://github.com/Aditya-Shitale/CloudNotebook" target="_blank">
          <Image src={im3} className="rounded-lg object-cover hover:scale-110 duration-300" w-full h-full layout="responsive" alt="" />
          <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-gray-800 opacity-70">
                <p className="text-lg text-orange-500 font-bold">CloudNotebook- your own ToDo list</p>
                  <p className="text-xs text-teal-500">This is site where you can login by your email address and password. You can perform add, update, delete your Notes (crud operations). Its on cloud so you can access it from anywhere. Build using frontend React-Js and MERN stack for backend part.</p>
             </div>
        </a>
      </div>
    </div>

     {/* ***************************TEXTEDITOR pic with info***************************** */}

    <div className="basis-1/3 flex-1">
      <div className="relative">
          <a href="https://github.com/Aditya-Shitale/TextEditor" target="_blank">
              <Image src={im4} className="rounded-lg object-cover hover:scale-110 duration-300" w-full h-full layout="responsive" alt="" />
              <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-gray-800 opacity-70">
                <p className="text-lg text-orange-500 font-bold">TEXT EDITS — editing a text</p>
                  <p className="text-xs text-teal-500"> This is a site where you can simply edit a text like making it all caps, all small, copy a text, minimum time required to read the entered text, and the number of words in the text, also there is a dark mode option. It is built using React js.</p>
             </div>
          </a>
      </div>
    </div>

 
            <div className="basis-1/3 flex-1">
              <Image
                src={im5}
                className="rounded-lg object-cover hover:scale-110 duration-300"
                w-full
                h-full
                layout="responsive"
                alt=""
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={im6}
                className="rounded-lg object-cover hover:scale-110 duration-300"
                w-full
                h-full
                layout="responsive"
                alt=""
              ></Image>
            </div>
          </div>
        </section>

        {/* ***************************SECTION 4 start FOOTER************************************* */}

        <section>
          <span className="flex justify-center py-5">
            {" "}
            <AiFillHeart className="text-red-600 text-xl " />
            <span className="text-teal-500 font-burtons text-sm ">
              Created By Aditya Shitale
            </span>
          </span>
        </section>
      </main>
    </div>
  );
}
