import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import adi from '../public/wave.png'
import design from  '../public/design.png'
import code from  '../public/code.png'
import consulting from  '../public/consulting.png'
import im1 from "../public/web1.png"
import im2 from "../public/web2.png"
import im3 from "../public/web3.png"
import im4 from "../public/web4.png"
import im5 from "../public/web5.png"
import im6 from "../public/web6.png"
import {useState} from "react";



export default function Home() {
  const [darkMode, setDarkMode]= useState(false);
  return (
    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>Aditya Shitale portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900' >
    <section className='min-h-screen'>
   <nav className='py-10 mb-12 flex justify-between'>
    <h1 className='text-xl font-burtons  dark:text-white'>DevelopedbyAdi</h1>
    <ul className='flex items-center'>
      <li className='cursor-pointer text-2xl'><BsFillMoonStarsFill  onClick={()=>setDarkMode(!darkMode)}  className=" dark:text-white" /></li>
      <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">
        Resume 
        </a></li>
    </ul>
   </nav>
   <div className='text-center p-10 '>
    <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Aditya Shitale</h2>
    <h3 className='text-2xl py-2 md:text-3xl  dark:text-white'>Developer and Coder.</h3>
    <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto  dark:text-white'>
      I am a student at Indian Institute of Information Technology,Kottayam, currently pursuing B.Tech in computer Science (2024),You can contact me from Clicking below.
     </p>
   </div>
   <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-white'>
    <AiFillTwitterCircle/>
    <AiFillLinkedin/>
    <AiFillGithub/>
   </div>
   <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
    <Image src={adi} alt="" layout="fill"  objectFit='cover'/>
   </div>

    </section>

    <section>

   <div>
    <h3 className='text-3xl py-1  dark:text-white'>Services I offfer</h3>
    <p className="text-md py-2 leading-8 text-gray-800  dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>       
   </div>

   <div className='lg:flex gap-10'>
    <div className='text-center shadow-lg p-10 rounded-xl  my-10  dark:bg-white'> 
     <Image src={design} alt="" width={100} height={100} />
     <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
     <p className='py-2'>
     Creating elegant designs suited for your needs following core
                design theory.
     </p>
     <h4 className='py-4 text-teal-600'>Design tools I use</h4>
     <p className='text-gray-800 py-1'>PhotoShop</p>
     <p className='text-gray-800 py-1'>Illustrator</p>
     <p className='text-gray-800 py-1'>Figma</p>
     <p className='text-gray-800 py-1'>tailwind</p>


    </div>
    <div className='text-center shadow-lg p-10 rounded-xl  my-10 dark:bg-white'> 
     <Image src={code} alt="" width={100} height={100} />
     <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
     <p className='py-2'>
     Creating elegant designs suited for your needs following core
                design theory.
     </p>
     <h4 className='py-4 text-teal-600'>Design tools I use</h4>
     <p className='text-gray-800 py-1'>PhotoShop</p>
     <p className='text-gray-800 py-1'>Illustrator</p>
     <p className='text-gray-800 py-1'>Figma</p>
     <p className='text-gray-800 py-1'>tailwind</p>


    </div>
    <div className='text-center shadow-lg p-10 rounded-xl  my-10 dark:bg-white'> 
     <Image src={consulting} alt="" width={100} height={100} />
     <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
     <p className='py-2'>
     Creating elegant designs suited for your needs following core
                design theory.
     </p>
     <h4 className='py-4 text-teal-600'>Design tools I use</h4>
     <p className='text-gray-800 py-1'>PhotoShop</p>
     <p className='text-gray-800 py-1'>Illustrator</p>
     <p className='text-gray-800 py-1'>Figma</p>
     <p className='text-gray-800 py-1'>tailwind</p>


    </div>
   </div>

    </section>

    <section>
  <div>
    <h3 className='text-3xl py-1  dark:text-white'>Portfolio</h3>
    <p className="text-md py-2 leading-8 text-gray-800  dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>  
  </div>
  <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap' >
   <div className='basis-1/3 flex-1'><Image src={im1} className="rounded-lg object-cover" w-full h-full layout="responsive"  alt=""></Image></div>
   <div className='basis-1/3 flex-1'><Image src={im2} className="rounded-lg object-cover" w-full h-full layout="responsive"  alt=""></Image></div>
   <div className='basis-1/3 flex-1'><Image src={im3} className="rounded-lg object-cover" w-full h-full  layout="responsive" alt=""></Image></div>
   <div className='basis-1/3 flex-1'><Image src={im4} className="rounded-lg object-cover" w-full h-full  layout="responsive" alt=""></Image></div>
   <div className='basis-1/3 flex-1'><Image src={im5} className="rounded-lg object-cover" w-full h-full  layout="responsive" alt=""></Image></div>
   <div className='basis-1/3 flex-1'><Image src={im6}  className="rounded-lg object-cover" w-full h-full layout="responsive" alt=""></Image></div>
  </div>


    </section>
      </main>

  
    </div>
  )
}
